name: CI/CD Pipeline

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    
    services: 
      docker: 
        image: docker:20.10.7
        options: --privileged

    steps:
    - name : Checkout code
      uses : actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build All services
      run: |
        for dir in auth-server config-server discovery gateway school student
          cd $dir 
          mvn clean install
        done

    - name: Build React client
      run: |
        cd ui/react-client
        npm install
        npm build
