name: CI/CD Pipeline

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    
    services: 
      docker: 
        image: docker:20.10.7
        options: --privileged
      
      postgres-school:
        image: postgres:15
        container_name: postgres-school-db
        environment:
          POSTGRES_DB: schools
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Abc@12345
        ports: 
          - "3306:3306"
        volumes:
          - school_pgdata: /var/lib/postgresql/data
      
      postgres-student:
        image: postgres:15
        container_name: postgres-student-db
        environment:
          POSTGRES_DB: students
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Abc@12345
        ports:
         - "3306:3306"
        volumes:
         - student_pgdata: /var/lib/postgresql/data
      
      volumes:
        school_pgdata:
        student_pgdata:

    steps:
    - name : Checkout code
      uses : actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build All services
      run: |
        for dir in config-server discovery gateway auth-server school student; do
          cd $dir 
          mvn clean install
          cd ..
        done

    - name: Build React client
      run: |
        cd ui/react-client
        npm install
        npm run build
